### ISSUE TITLE
Deploy Your Multi-Target Application (MTA)

### ISSUE THREAD

**Issue by ceedee666** [sap-tutorials/Issues#673]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html
--------------------------

In the 5th step of the tutorial the mty.yaml is created. This file contains the following:

```
type: com.sap.xs.hdi-container
    parameters:
    service: hana  # or 'hanatrial' on trial landscapes
    service-plan: hdi-shared
```
The tutorial should contain an hint, that this needs to be changed on the trial landscape.
Furthermore, the tutorial assumes the availability of an instance of the "SAP HANA Schemas & HDI Containers" service with the plan hdi-shared. If I'm not mistaken this was not created in any of the previous tutorials. Creating this instance should probably be a separate step in the tutorial.
